# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bhavesh_Practical' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bhavesh_Practical
pod 'Alamofire', '~> 4.7'
pod 'Kingfisher', '~> 5.0'
pod 'MBProgressHUD', '~> 1.1.0'

  target 'Bhavesh_PracticalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Bhavesh_PracticalUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
